monolog:
    handlers:
        main:
            type: rotating_file
            level: debug
            action_level: debug
            max_files: 90
            handler: nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.eccube_log
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
